single line if

diff --git a/.github/workflows/vuln_scan.yaml b/.github/workflows/vuln_scan.yaml
--- a/.github/workflows/vuln_scan.yaml
+++ b/.github/workflows/vuln_scan.yaml
@@ -25,13 +25,9 @@ jobs:
       - name: Scan
         id: test
         run: |
-          bearer scan ./demoapp --fail-on-severity critical > /tmp/scan-output
-          if $?; then
-            echo "scan complete - no critical vulnerabilities"
-          else
-            echo "scan complete - critical vulnerabilities found!"
-            touch /tmp/shouldfail
-          fi
+          bearer scan ./demoapp --fail-on-severity critical &> /tmp/scan-output
+          cat /tmp/scan-output
+          if $?; then echo "scan complete - no critical vulnerabilities"; else echo "scan complete - critical vulnerabilities found!"; touch /tmp/shouldfail; fi
 
       - name: Upload scan to S3
         run: |
@@ -40,6 +36,4 @@ jobs:
 
       - name: Fail on scan failure
         run: |
-          if [ -f /tmp/shouldfail ];
-            exit 1
-          fi
+          if [ -f /tmp/shouldfail ]; then exit 1; fi
